name: Build Image and Test
on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/386
            runner: ubuntu-latest
          - platform: linux/arm/v6
            runner: ubuntu-24.04-arm
          - platform: linux/arm/v7
            runner: ubuntu-24.04-arm
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
          - platform: linux/riscv64
            runner: ubuntu-24.04-arm
    env:
      CI_ARCH: ${{ matrix.platform }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: "3.13"
    
    - name: Run black formatter
      run: |
        pip install black
        black --check --diff test/tests/

    - name: Install wheel
      run:  pip install wheel

    - name: Install dependencies
      run: pip install -r test/requirements.txt

    - name: Test with tox
      run: |
        CIPLATFORM=${{ env.CI_ARCH }} tox -c test/tox.ini
